redir-port: 7891
tproxy-port: 7894
port: 8080
socks-port: 1080
mixed-port: 7890
mode: rule
log-level: silent
allow-lan: true
tcp-concurrent: true
unified-delay: true
geodata-loader: memconservative
keep-alive-interval: 15
keep-alive-idle: 600
disable-keep-alive: false
external-controller: 0.0.0.0:9090
secret: ''
bind-address: 0.0.0.0
external-ui: "ui"
enable-process: true
find-process-mode: always
ipv6: false
experimental:
  quic-go-disable-gso: true
  quic-go-disable-ecn: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
#  fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:7874
  respect-rules: true
  default-nameserver:
    - "system"
  nameserver:
    - "208.67.222.222"
    - "223.5.5.5"
  proxy-server-nameserver:
    - "system"
    #- "112.215.198.254"
    #- "112.215.198.248"
#  fake-ip-filter-mode: blacklist
#  fake-ip-filter:
#    - "+.lan"
#    - "+.local"
#    - "google.com"
#    - "*.google.com"
tun:
  enable: true
  auto-route: false
  auto-redirect: false
  auto-detect-interface: false
  device: Meta
  stack: system
  mtu: 1500
  gso: true
  gso-max-size: 65536
  endpoint-independent-nat: true
  dns-hijack:
    - "tcp://any:53"
    - "udp://any:53"
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  sniff:
    HTTP:
      port:
        - "80"
        - "8080"
      override-destination: true
    TLS:
      port:
        - "443"
        - "8443"
profile:
  store-selected: true
#  store-fake-ip: true
  force-domain:
    - "+.netflix.com"
  skip-domain:
    - "+.facebook.com"
rule-providers:
  R_NSFW:
    type: http
    behavior: domain
    format: mrs
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/refs/heads/release/nsfw.mrs"
    path: "./rules/nsfw.mrs"
    interval: 86400
  R_ADS_ALL:
    type: http
    behavior: domain
    format: mrs
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/refs/heads/release/category-ads-all.mrs"
    path: "./rules/category-ads-all.mrs"
    interval: 86400
proxy-providers:
  Proxy:
    type: file
    path: "./proxy/Akun.yaml"
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 60
proxy-groups:
  - name: Internet
    type: select
    disable-udp: false
    use:
      - Proxy
  - name: FallBack
    type: fallback
    disable-udp: false
    use:
      - Proxy
    url: https://www.gstatic.com/generate_204
    interval: 60
rules:
  - RULE-SET,R_ADS_ALL,REJECT
  - RULE-SET,R_NSFW,REJECT
  - MATCH,GLOBAL
